export const privateMaids = [
  {
    name: 'AmberTwilight',
    set: 1,
    type: 'privateMaid',
    cost: 5,
    vp: -3,
    onEndOfEveryTurn: () => {},
  },
  {
    name: 'NordTwilight',
    set: 1,
    type: 'privateMaid',
    cost: 4,
    vp: -4,
    onStart: () => {},
  },
  {
    name: 'SoraNakachi',
    set: 1,
    type: 'privateMaid',
    cost: 7,
    vp: 2,
    onStart: () => {},
  },
  {
    name: 'FayLongfang',
    set: 1,
    type: 'privateMaid',
    cost: 6,
    vp: 0,
    onStart: () => {},
  },
  {
    name: 'LalandeDreyfus',
    set: 1,
    type: 'privateMaid',
    cost: 6,
    vp: 2,
    onStart: () => {},
  },
  {
    name: 'MillyViolet',
    set: 1,
    type: 'privateMaid',
    cost: 5,
    vp: 2,
    onPlayPhase: () => {},
  },
  {
    name: 'EugenieFontaine',
    set: 1,
    type: 'privateMaid',
    cost: 5,
    vp: 0,
    onStart: () => {},
  },
  {
    name: 'LucienneDeMarlboro',
    set: 1,
    type: 'privateMaid',
    cost: 5,
    vp: 1,
    onStart: () => {},
  },
  {
    name: 'RosaTopaz',
    set: 1,
    type: 'privateMaid',
    cost: 5,
    vp: 1,
    onStart: () => {},
  },
  {
    name: 'TanyaPetrushka',
    set: 1,
    type: 'privateMaid',
    cost: 4,
    vp: 1,
    onPlayPhase: () => {},
  },
];
