import { playFuncs } from './set1Functions';
import { eventFuncs } from './set1ChamberFuncs';
import { vpFuncs } from './vpFunctions';

export const set1Fixed = [
  {
    name: 'Illness',
    set: 1,
    type: 'event',
    cost: 4,
    quantity: 10,
    attachTo: 'maid',
    onStart: eventFuncs.Illness,
    restric: eventFuncs.restricIllness,
  },
  {
    name: 'BadHabit',
    set: 1,
    type: 'event',
    cost: 2,
    vp: vpFuncs.BadHabit,
    quantity: 16,
  },
  {
    name: 'ColetteFramboise',
    set: 1,
    type: 'maidChief',
    cost: 3,
    vp: vpFuncs.Colette,
    chamberCost: 2,
    quantity: 24,
  },
  {
    name: 'MarianneSoleil',
    set: 1,
    type: 'maidChief',
    cost: 9,
    vp: (chamber, deck) => 6 * (chamber + deck),
    quantity: 8,
  },
];

export const set1Maids = [
  {
    name: 'AniseGreenaway',
    set: 1,
    type: 'maid',
    cost: 7,
    vp: (chamber, deck) => 3 * deck,
    draw: 3,
    contract: 1,
    quantity: 8,
  },
  {
    name: 'OpheliaGrail',
    set: 1,
    type: 'maid',
    cost: 6,
    draw: 1,
    servings: 1,
    love: 1,
    contract: 1,
    vp: vpFuncs.Ophelia,
    quantity: 8,
  },
  {
    name: 'SainsburyLockwood',
    set: 1,
    type: 'maid',
    cost: 5,
    onPlay: playFuncs.Sainsbury,
    quantity: 10,
  },
  {
    name: 'TenalysTrent',
    set: 1,
    type: 'maid',
    cost: 5,
    love: 3,
    contract: 1,
    onPlay: playFuncs.Tenalys,
    forcedAction: playFuncs.actionTenalys,
    quantity: 10,
  },
  {
    name: 'NenaWilder',
    set: 1,
    type: 'maid',
    cost: 5,
    love: 1,
    onPlay: playFuncs.Nena,
    quantity: 10,
  },
  {
    name: 'NatsumiFujikawa',
    set: 1,
    type: 'maid',
    cost: 5,
    draw: 1,
    servings: 2,
    onPlay: playFuncs.Natsumi,
    forcedAction: playFuncs.actionNatsumi,
    quantity: 10,
  },
  {
    name: 'EsquineForet',
    set: 1,
    type: 'maid',
    cost: 4,
    draw: 2,
    onPlay: playFuncs.Esquine,
    quantity: 2,
  },
  {
    name: 'GenevieveDaubigny',
    set: 1,
    type: 'maid',
    cost: 4,
    draw: 1,
    servings: 1,
    love: 1,
    quantity: 2,
  },
  {
    name: 'MoineDeLefevre',
    set: 1,
    type: 'maid',
    cost: 4,
    draw: 2,
    contract: 2,
    quantity: 2,
  },
  {
    name: 'ElizaRosewater',
    set: 1,
    type: 'maid',
    cost: 3,
    love: 2,
    onPlay: playFuncs.Eliza,
    forcedAction: playFuncs.ElizaDiscard,
    quantity: 2,
  },
  {
    name: 'SafranVirginie',
    set: 1,
    type: 'maid',
    cost: 3,
    vp: vpFuncs.Safran,
    love: 2,
    chamberCost: 1,
    quantity: 10,
  },
  {
    name: 'KagariIchinomiya',
    set: 1,
    type: 'maid',
    cost: 3,
    servings: 2,
    quantity: 2,
  },
  {
    name: 'ClaireSaintJuste',
    set: 1,
    type: 'maid',
    cost: 3,
    servings: 1,
    onPlay: playFuncs.Claire,
    onDefend: playFuncs.ClaireDefend,
    quantity: 2,
  },
  {
    name: 'AzureCrescent',
    set: 1,
    type: 'maid',
    cost: 2,
    vp: vpFuncs.Azure,
    contract: 1,
    chamberCost: 1,
    quantity: 10,
  },
  {
    name: 'ViolaCrescent',
    set: 1,
    type: 'maid',
    cost: 2,
    vp: vpFuncs.Viola,
    draw: 1,
    chamberCost: 1,
    quantity: 10,
  },
  {
    name: 'RougeCrescent',
    set: 1,
    type: 'maid',
    cost: 2,
    vp: vpFuncs.Rouge,
    love: 1,
    chamberCost: 1,
    quantity: 10,
  },
];
