export const set1Fixed = [
  {
    name: 'Illness',
    set: 1,
    type: 'event',
    cost: 4,
    quantity: 10,
    attachTo: 'maid',
  },
  {
    name: 'BadHabit',
    set: 1,
    type: 'event',
    cost: 2,
    vp: () => {},
    quantity: 16,
  },
  {
    name: 'ColetteFramboise',
    set: 1,
    type: 'maidChief',
    cost: 3,
    vp: () => {},
    chamberCost: 2,
    quantity: 24,
  },
  {
    name: 'MarianneSoleil',
    set: 1,
    type: 'maidChief',
    cost: 9,
    vp: 6,
    quantity: 8,
  },
];

export const set1Maids = [
  {
    name: 'AniseGreenaway',
    set: 1,
    type: 'maid',
    cost: 7,
    vp: 3,
    draw: 3,
    contract: 1,
    quantity: 8,
  },
  {
    name: 'OpheliaGrail',
    set: 1,
    type: 'maid',
    cost: 6,
    draw: 1,
    servings: 1,
    love: 1,
    contract: 1,
    vp: () => {},
    quantity: 8,
  },
  {
    name: 'SainsburyLockwood',
    set: 1,
    type: 'maid',
    cost: 5,
    onPlay: () => {},
    quantity: 10,
  },
  {
    name: 'TenalysTrent',
    set: 1,
    type: 'maid',
    cost: 5,
    love: 3,
    contract: 1,
    onPlay: () => {},
    quantity: 10,
  },
  {
    name: 'NenaWilder',
    set: 1,
    type: 'maid',
    cost: 5,
    love: 1,
    onPlay: () => {},
    quantity: 10,
  },
  {
    name: 'NatsumiFujikawa',
    set: 1,
    type: 'maid',
    cost: 5,
    draw: 1,
    servings: 2,
    onPlay: () => {},
    quantity: 10,
  },
  {
    name: 'EsquineForet',
    set: 1,
    type: 'maid',
    cost: 4,
    draw: 2,
    onPlay: () => {},
    quantity: 10,
  },
  {
    name: 'GenevieveDaubigny',
    set: 1,
    type: 'maid',
    cost: 4,
    draw: 1,
    servings: 1,
    love: 1,
    quantity: 10,
  },
  {
    name: 'MoineDeLefevre',
    set: 1,
    type: 'maid',
    cost: 4,
    draw: 2,
    contract: 2,
    quantity: 10,
  },
  {
    name: 'ElizaRosewater',
    set: 1,
    type: 'maid',
    cost: 3,
    love: 2,
    onPlay: () => {},
    quantity: 10,
  },
  {
    name: 'SafranVirginie',
    set: 1,
    type: 'maid',
    cost: 3,
    vp: () => {},
    love: 2,
    chamberCost: 1,
    quantity: 10,
  },
  {
    name: 'KagariIchinomiya',
    set: 1,
    type: 'maid',
    cost: 3,
    servings: 2,
    quantity: 10,
  },
  {
    name: 'ClaireSaintJuste',
    set: 1,
    type: 'maid',
    cost: 3,
    servings: 1,
    onPlay: () => {},
    whileInHand: () => {},
    quantity: 10,
  },
  {
    name: 'AzureCrescent',
    set: 1,
    type: 'maid',
    cost: 2,
    vp: () => {},
    contract: 1,
    chamberCost: 1,
    quantity: 10,
  },
  {
    name: 'ViolaCrescent',
    set: 1,
    type: 'maid',
    cost: 2,
    vp: () => {},
    draw: 1,
    chamberCost: 1,
    quantity: 10,
  },
  {
    name: 'RougeCrescent',
    set: 1,
    type: 'maid',
    cost: 2,
    vp: () => {},
    love: 1,
    chamberCost: 1,
    quantity: 10,
  },
];
