import { playFuncs } from './set1Functions';

export const set3Fixed = [
  {
    name: 'BeatriceEscudo',
    set: 3,
    type: 'maidChief',
    cost: 3,
    vp: (chamber, deck) => 2 * chamber,
    chamberCost: 2,
    quantity: 24,
  },
  {
    name: 'SophiaMarfil',
    set: 3,
    type: 'maidChief',
    cost: 8,
    vp: (chamber, deck) => 5 * (chamber + deck),
    quantity: 8,
  },
];

export const set3Maids = [
  {
    name: 'FridaViento',
    set: 3,
    type: 'maid',
    cost: 7,
    draw: 2,
    love: 2,
    contract: 2,
    quantity: 8,
  },
  {
    name: 'ClorindeSea',
    set: 3,
    type: 'maid',
    cost: 6,
    draw: 1,
    servings: 2,
    vp: () => {},
    quantity: 8,
  },
  {
    name: 'Laura',
    set: 3,
    type: 'maid',
    cost: 6,
    draw: 2,
    onPlay: () => {},
    quantity: 8,
  },
  {
    name: 'LydiaLeon',
    set: 3,
    type: 'maid',
    cost: 5,
    servings: 1,
    onPlay: () => {},
    quantity: 10,
  },
  {
    name: 'CynthiaLakes',
    set: 3,
    type: 'maid',
    cost: 5,
    draw: 4,
    onPlay: playFuncs.Tenalys,
    forcedAction: playFuncs.actionTenalys,
    quantity: 10,
  },
  {
    name: 'FlorenceSpring',
    set: 3,
    type: 'maid',
    cost: 5,
    vp: () => {},
    love: 2,
    chamberCost: 1,
    quantity: 10,
  },
  {
    name: 'RominaVautrin',
    set: 3,
    type: 'maid',
    cost: 4,
    draw: 2,
    love: 2,
    onPlay: (inst) => inst.context.updateParent({ gameState: 'contractPhase' }),
    quantity: 10,
  },
  {
    name: 'CaldinaAlley',
    set: 3,
    type: 'maid',
    cost: 4,
    draw: 2,
    onPlay: () => {},
    forcedAction: () => {},
    quantity: 10,
  },
  {
    name: 'RiyaNagarasi',
    set: 3,
    type: 'maid',
    cost: 4,
    draw: 2,
    onPlay: () => {},
    quantity: 10,
  },
  {
    name: 'ChinatsuKooriyama',
    set: 3,
    type: 'maid',
    cost: 4,
    onPlay: () => {},
    quantity: 10,
  },
  {
    name: 'FeaPrimrose',
    set: 3,
    type: 'maid',
    cost: 4,
    servings: 2,
    contract: 1,
    quantity: 10,
  },
  {
    name: 'MargaretaTorente',
    set: 3,
    type: 'maid',
    cost: 3,
    vp: (chamber, deck) => {},
    draw: 1,
    love: 1,
    servings: 1,
    quantity: 10,
  },
  {
    name: 'EvitaCatala',
    set: 3,
    type: 'maid',
    cost: 3,
    love: 1,
    servings: 1,
    onPlay: () => {},
    forcedAction: () => {},
    quantity: 10,
  },
  {
    name: 'ValenciaPretre',
    set: 3,
    type: 'maid',
    cost: 3,
    vp: (chamber, deck) => chamber + deck,
    onStart: () => {},
    love: 2,
    chamberCost: 1,
    quantity: 10,
  },
  {
    name: 'DaphneCoraille',
    set: 3,
    type: 'maid',
    cost: 3,
    servings: 1,
    onPlay: () => {},
    quantity: 10,
  },
  {
    name: 'GermaineMahle',
    set: 3,
    type: 'maid',
    cost: 3,
    draw: 2,
    onPlay: () => {},
    quantity: 10,
  },
  {
    name: 'NonnetteLarge',
    set: 3,
    type: 'maid',
    cost: 2,
    draw: 2,
    contract: 1,
    onPlay: () => {},
    quantity: 10,
  },
  {
    name: 'HyacinthArrow',
    set: 3,
    type: 'maid',
    cost: 2,
    vp: () => {},
    love: 1,
    chamberCost: 1,
    quantity: 10,
  },
];
